-- Atualizar vw_propostas para calcular dias_aberta baseado no campo data (data real de envio)
-- ao invés de created_at (data de entrada no sistema)

DROP VIEW IF EXISTS public.vw_insights_pool;
DROP VIEW IF EXISTS public.vw_propostas;

CREATE VIEW public.vw_propostas AS
SELECT 
  p.id,
  p.user_id,
  p.created_at,
  p.data AS periodo_dia,
  to_char(p.data::timestamp with time zone, 'YYYY-MM'::text) AS periodo_mes,
  EXTRACT(year FROM p.data)::integer AS periodo_ano,
  cl.nome AS cliente,
  cl.cidade,
  cl.bairro,
  l.origem AS canal,
  p.tipo_piso AS servico,
  p.m2,
  COALESCE(p.valor_total, 0::numeric) AS valor_total,
  COALESCE(p.liquido, 0::numeric) AS valor_liquido,
  CASE
    WHEN COALESCE(p.valor_total, 0::numeric) > 0::numeric 
    THEN COALESCE(p.liquido, 0::numeric) / p.valor_total * 100::numeric
    ELSE 0::numeric
  END AS margem_pct,
  p.status,
  p.forma_pagamento,
  p.desconto,
  -- Calcula dias aberta baseado na data real de envio da proposta (p.data)
  EXTRACT(day FROM now() - p.data::timestamp with time zone)::integer AS dias_aberta
FROM propostas p
JOIN clientes cl ON cl.id = p.cliente_id
LEFT JOIN leads l ON l.id = p.lead_id;

-- Recriar vw_insights_pool que depende de vw_propostas
CREATE VIEW public.vw_insights_pool AS
SELECT 
  vw_propostas.user_id,
  'proposta'::text AS tipo,
  vw_propostas.id AS id_origem,
  vw_propostas.created_at,
  vw_propostas.periodo_dia,
  vw_propostas.periodo_mes,
  vw_propostas.periodo_ano,
  vw_propostas.status,
  vw_propostas.cliente,
  vw_propostas.canal,
  vw_propostas.servico,
  vw_propostas.bairro,
  vw_propostas.cidade,
  COALESCE(vw_propostas.m2, 0::numeric) AS m2,
  COALESCE(vw_propostas.valor_total, 0::numeric) AS valor_total,
  COALESCE(vw_propostas.valor_liquido, 0::numeric) AS valor_liquido,
  NULL::numeric AS valor,
  NULL::integer AS numero_parcela,
  NULL::date AS vencimento,
  NULL::date AS pago_em,
  COALESCE(vw_propostas.margem_pct, 0::numeric) AS margem_pct,
  vw_propostas.forma_pagamento,
  vw_propostas.dias_aberta,
  NULL::text AS estagio,
  NULL::text AS motivo_perda,
  NULL::integer AS dias_no_funil,
  NULL::integer AS first_response_minutes,
  NULL::numeric AS progresso_pct,
  NULL::boolean AS realizada,
  NULL::text AS responsavel
FROM vw_propostas
UNION ALL
SELECT 
  vw_vendas.user_id,
  'venda'::text AS tipo,
  vw_vendas.id AS id_origem,
  vw_vendas.created_at,
  vw_vendas.periodo_dia,
  vw_vendas.periodo_mes,
  vw_vendas.periodo_ano,
  vw_vendas.status::text AS status,
  vw_vendas.cliente,
  vw_vendas.canal,
  vw_vendas.servico,
  vw_vendas.bairro,
  vw_vendas.cidade,
  COALESCE(vw_vendas.m2, 0::numeric) AS m2,
  COALESCE(vw_vendas.valor_total, 0::numeric) AS valor_total,
  COALESCE(vw_vendas.valor_liquido, 0::numeric) AS valor_liquido,
  NULL::numeric AS valor,
  NULL::integer AS numero_parcela,
  NULL::date AS vencimento,
  NULL::date AS pago_em,
  COALESCE(vw_vendas.margem_pct, 0::numeric) AS margem_pct,
  vw_vendas.forma_pagamento,
  NULL::integer AS dias_aberta,
  NULL::text AS estagio,
  NULL::text AS motivo_perda,
  NULL::integer AS dias_no_funil,
  NULL::integer AS first_response_minutes,
  NULL::numeric AS progresso_pct,
  NULL::boolean AS realizada,
  NULL::text AS responsavel
FROM vw_vendas
UNION ALL
SELECT 
  vw_financeiro.user_id,
  'financeiro'::text AS tipo,
  vw_financeiro.id AS id_origem,
  vw_financeiro.created_at,
  vw_financeiro.periodo_dia,
  vw_financeiro.periodo_mes,
  vw_financeiro.periodo_ano,
  vw_financeiro.status::text AS status,
  vw_financeiro.cliente,
  NULL::text AS canal,
  NULL::text AS servico,
  vw_financeiro.bairro,
  vw_financeiro.cidade,
  0 AS m2,
  COALESCE(vw_financeiro.valor_bruto, 0::numeric) AS valor_total,
  COALESCE(vw_financeiro.valor, 0::numeric) AS valor_liquido,
  COALESCE(vw_financeiro.valor, 0::numeric) AS valor,
  vw_financeiro.numero_parcela,
  vw_financeiro.periodo_dia AS vencimento,
  vw_financeiro.data_pagamento AS pago_em,
  COALESCE(vw_financeiro.margem_pct, 0::numeric) AS margem_pct,
  vw_financeiro.forma AS forma_pagamento,
  vw_financeiro.dias_atraso AS dias_aberta,
  NULL::text AS estagio,
  NULL::text AS motivo_perda,
  NULL::integer AS dias_no_funil,
  NULL::integer AS first_response_minutes,
  NULL::numeric AS progresso_pct,
  NULL::boolean AS realizada,
  NULL::text AS responsavel
FROM vw_financeiro
UNION ALL
SELECT 
  vw_leads.user_id,
  'lead'::text AS tipo,
  vw_leads.id AS id_origem,
  vw_leads.created_at,
  vw_leads.periodo_dia,
  vw_leads.periodo_mes,
  vw_leads.periodo_ano,
  vw_leads.estagio::text AS status,
  vw_leads.cliente,
  vw_leads.canal,
  vw_leads.servico,
  vw_leads.bairro,
  vw_leads.cidade,
  COALESCE(vw_leads.m2, 0::numeric) AS m2,
  COALESCE(vw_leads.valor_potencial, 0::numeric) AS valor_total,
  0 AS valor_liquido,
  NULL::numeric AS valor,
  NULL::integer AS numero_parcela,
  NULL::date AS vencimento,
  NULL::date AS pago_em,
  0 AS margem_pct,
  NULL::text AS forma_pagamento,
  NULL::integer AS dias_aberta,
  vw_leads.estagio::text AS estagio,
  vw_leads.motivo_perda,
  vw_leads.dias_no_funil,
  vw_leads.first_response_minutes,
  NULL::numeric AS progresso_pct,
  NULL::boolean AS realizada,
  vw_leads.responsavel
FROM vw_leads
UNION ALL
SELECT 
  vw_obras.user_id,
  'obra'::text AS tipo,
  vw_obras.id AS id_origem,
  vw_obras.created_at,
  vw_obras.periodo_dia,
  vw_obras.periodo_mes,
  vw_obras.periodo_ano,
  vw_obras.status::text AS status,
  vw_obras.cliente,
  NULL::text AS canal,
  vw_obras.servico,
  vw_obras.bairro,
  vw_obras.cidade,
  COALESCE(vw_obras.m2, 0::numeric) AS m2,
  COALESCE(vw_obras.valor_total, 0::numeric) AS valor_total,
  0 AS valor_liquido,
  NULL::numeric AS valor,
  NULL::integer AS numero_parcela,
  NULL::date AS vencimento,
  NULL::date AS pago_em,
  0 AS margem_pct,
  NULL::text AS forma_pagamento,
  NULL::integer AS dias_aberta,
  NULL::text AS estagio,
  NULL::text AS motivo_perda,
  NULL::integer AS dias_no_funil,
  NULL::integer AS first_response_minutes,
  vw_obras.progresso_pct,
  NULL::boolean AS realizada,
  vw_obras.responsavel_obra AS responsavel
FROM vw_obras
UNION ALL
SELECT 
  vw_visitas.user_id,
  'visita'::text AS tipo,
  vw_visitas.id AS id_origem,
  vw_visitas.created_at,
  vw_visitas.periodo_dia,
  vw_visitas.periodo_mes,
  vw_visitas.periodo_ano,
  vw_visitas.status::text AS status,
  vw_visitas.cliente,
  vw_visitas.canal,
  vw_visitas.servico,
  vw_visitas.bairro,
  vw_visitas.cidade,
  COALESCE(vw_visitas.m2, 0::numeric) AS m2,
  0 AS valor_total,
  0 AS valor_liquido,
  NULL::numeric AS valor,
  NULL::integer AS numero_parcela,
  NULL::date AS vencimento,
  NULL::date AS pago_em,
  0 AS margem_pct,
  NULL::text AS forma_pagamento,
  NULL::integer AS dias_aberta,
  NULL::text AS estagio,
  NULL::text AS motivo_perda,
  NULL::integer AS dias_no_funil,
  NULL::integer AS first_response_minutes,
  NULL::numeric AS progresso_pct,
  vw_visitas.realizada,
  vw_visitas.responsavel
FROM vw_visitas;